export const KAYNAKLAR = {
  USGS: 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude=1&minlatitude=35&maxlatitude=43&minlongitude=25&maxlongitude=45&orderby=time&limit=50',
  MGM: 'https://www.mgm.gov.tr/json/uyarilar.aspx',
  AFAD_UYARI: 'https://www.afad.gov.tr/rss/duyuru.xml',
  NTV_RSS: 'https://www.ntv.com.tr/gundem.rss',
  CNN_TURK_RSS: 'https://www.cnnturk.com/feed/rss/turkiye/news',
  HURRIYET_RSS: 'https://www.hurriyet.com.tr/rss/gundem',
  SABAH_RSS: 'https://www.sabah.com.tr/rss/gundem.xml',
  SOZCU_RSS: 'https://www.sozcu.com.tr/rss/gundem.xml',
  TCMB_DOVIZ: 'https://www.tcmb.gov.tr/kurlar/today.xml',
  KGM_RSS: 'https://www.kgm.gov.tr/rss/YolDurumu.aspx',
}

export const KATEGORI_RENK: Record<string, string> = {
  DEPREM: '#FF4444', DEPREM_ARTCI: '#FF6666', YANGIN: '#FF6B00',
  ORMAN_YANGINI: '#FF8C00', SEL: '#0066FF', TAŞKIN: '#0088FF',
  KAR_FIRTINASI: '#88CCFF', HORTUM: '#AA44FF', HEYELAN: '#8B4513',
  TSUNAMI: '#0000FF', DOLU: '#44AAFF', SICAK_HAVA: '#FF2200',
  DON: '#AADDFF', SIS: '#AAAAAA', DEPREM_RISK: '#FF8888',
  GUVENLIK: '#FF0000', ASKER: '#556B2F', SINIR: '#8B0000',
  TEROR: '#CC0000', OPERASYON: '#006400', PROTESTO: '#FFD700',
  GOSTERI: '#FFA500', TUTUKLAMA: '#800000', KURTARMA: '#00AA00',
  KACAKCILIK: '#4B0082', UYUSTURUCU: '#800080',
  TRAFIK_KAZA: '#FF8800', YOL_KAPALI: '#FF6600', HAVA_ULASIM: '#00BFFF',
  DENIZ_ULASIM: '#006994', TREN_KAZA: '#8B4513', METRO: '#FF69B4',
  KOPRU: '#A0522D', ELEKTRIK_KESINTI: '#FFD700', DOGALGAZ_KESINTI: '#FF8C00',
  SU_KESINTI: '#00CED1', INTERNET_KESINTI: '#7B68EE', BINA_COKME: '#8B0000',
  INSAAT_KAZA: '#D2691E', MADEN_KAZA: '#2F4F4F', ALTYAPI: '#708090',
  DOVIZ: '#32CD32', FAIZ: '#228B22', BORSA: '#00FF7F',
  ENFLASYON: '#FF4500', GREV: '#DC143C', IFLAS: '#B22222',
  IHRACAT: '#3CB371', DOGALGAZ_FIYAT: '#DAA520',
  SALGIN: '#9400D3', HASTANE: '#FF1493', ZEHIRLENME: '#8B008B',
  GIDA_ZEHIRLENMESI: '#9B59B6', SAGLIK_BAKANLIGI: '#E91E63',
  HAVA_KIRLILIGI: '#696969', DENIZ_KIRLILIGI: '#191970',
  ORMAN_TAHRIBAT: '#228B22', HAYVAN_SALGINI: '#8FBC8F', NUKLEER: '#ADFF2F',
  SIYASET: '#4169E1', MECLIS: '#1E90FF', SECIM: '#00BFFF',
  MAHKEME: '#483D8B', YOLSUZLUK: '#8B0000', AFAD_UYARI: '#FF4500',
  EGITIM: '#20B2AA', SPOR: '#00FA9A', KULTUR: '#DDA0DD',
  DIN: '#C8A951', GOCMEN: '#F4A460',
  SIBER_SALDIRI: '#00FF00', TEKNOLOJI: '#00CED1',
  // YENİ KATEGORİLER
  CATISMA: '#CC0000', SIVIL_SIDDET: '#FF0055', AYAKLANMA: '#FF3300',
  STRATEJIK: '#4444FF', FIRTINA: '#4499FF', VOLKAN: '#FF2200',
  KASIRGA: '#CC00FF', KURAKLIK: '#FFAA00', TOZ_FIRTINASI: '#AA8844',
  SICAK_DALGA: '#FF5500', DENIZ_OLAYI: '#0066CC', INSAN_KAYNAKLI: '#884400',
  'HAVA_KALİTESİ': '#696969',
  DIGER: '#808080',
}

export const KATEGORI_ISIM: Record<string, string> = {
  DEPREM: '🔴 Deprem', DEPREM_ARTCI: '🔴 Artçı Deprem',
  YANGIN: '🔥 Yangın', ORMAN_YANGINI: '🔥 Orman Yangını',
  SEL: '🌊 Sel', TAŞKIN: '🌊 Taşkın', KAR_FIRTINASI: '❄️ Kar Fırtınası',
  HORTUM: '🌪️ Hortum', HEYELAN: '⛰️ Heyelan', TSUNAMI: '🌊 Tsunami',
  DOLU: '🌨️ Dolu', SICAK_HAVA: '🌡️ Aşırı Sıcak', DON: '🧊 Don',
  SIS: '🌫️ Sis', DEPREM_RISK: '⚠️ Deprem Riski',
  GUVENLIK: '🚨 Güvenlik', ASKER: '🪖 Askeri', SINIR: '🛡️ Sınır',
  TEROR: '💥 Terör', OPERASYON: '🎯 Operasyon', PROTESTO: '✊ Protesto',
  GOSTERI: '📢 Gösteri', TUTUKLAMA: '🔒 Tutuklama', KURTARMA: '🚁 Kurtarma',
  KACAKCILIK: '🚫 Kaçakçılık', UYUSTURUCU: '💊 Uyuşturucu',
  TRAFIK_KAZA: '🚗 Trafik Kazası', YOL_KAPALI: '🚧 Yol Kapalı',
  HAVA_ULASIM: '✈️ Hava Ulaşım', DENIZ_ULASIM: '🚢 Deniz Ulaşım',
  TREN_KAZA: '🚂 Tren Kazası', METRO: '🚇 Metro', KOPRU: '🌉 Köprü',
  ELEKTRIK_KESINTI: '⚡ Elektrik Kesintisi', DOGALGAZ_KESINTI: '🔥 Doğalgaz Kesintisi',
  SU_KESINTI: '💧 Su Kesintisi', INTERNET_KESINTI: '📡 İnternet Kesintisi',
  BINA_COKME: '🏚️ Bina Çökmesi', INSAAT_KAZA: '🏗️ İnşaat Kazası',
  MADEN_KAZA: '⛏️ Maden Kazası', ALTYAPI: '🔧 Altyapı',
  DOVIZ: '💵 Döviz', FAIZ: '📈 Faiz', BORSA: '📊 Borsa',
  ENFLASYON: '💸 Enflasyon', GREV: '✊ Grev', IFLAS: '📉 İflas',
  IHRACAT: '🚢 İhracat', DOGALGAZ_FIYAT: '⛽ Doğalgaz Fiyatı',
  SALGIN: '🦠 Salgın', HASTANE: '🏥 Hastane', ZEHIRLENME: '☠️ Zehirlenme',
  GIDA_ZEHIRLENMESI: '🍽️ Gıda Zehirlenmesi', SAGLIK_BAKANLIGI: '💊 Sağlık Bakanlığı',
  HAVA_KIRLILIGI: '😷 Hava Kirliliği', DENIZ_KIRLILIGI: '🌊 Deniz Kirliliği',
  ORMAN_TAHRIBAT: '🌳 Orman Tahribatı', HAYVAN_SALGINI: '🐄 Hayvan Salgını',
  NUKLEER: '☢️ Nükleer', SIYASET: '🏛️ Siyaset', MECLIS: '🏛️ Meclis',
  SECIM: '🗳️ Seçim', MAHKEME: '⚖️ Mahkeme', YOLSUZLUK: '💰 Yolsuzluk',
  AFAD_UYARI: '🚨 AFAD Uyarı', EGITIM: '📚 Eğitim', SPOR: '⚽ Spor',
  KULTUR: '🎭 Kültür', DIN: '🕌 Din', GOCMEN: '🚶 Göçmen',
  SIBER_SALDIRI: '💻 Siber Saldırı', TEKNOLOJI: '🤖 Teknoloji',
  CATISMA: '⚔️ Çatışma', SIVIL_SIDDET: '🩸 Sivil Şiddet', AYAKLANMA: '🔥 Ayaklanma',
  STRATEJIK: '🎖️ Stratejik Gelişme', FIRTINA: '⛈️ Fırtına', VOLKAN: '🌋 Volkan',
  KASIRGA: '🌀 Kasırga', KURAKLIK: '🏜️ Kuraklık', TOZ_FIRTINASI: '💨 Toz Fırtınası',
  SICAK_DALGA: '🌡️ Sıcak Dalga', DENIZ_OLAYI: '🌊 Deniz Olayı',
  INSAN_KAYNAKLI: '⚠️ İnsan Kaynaklı', 'HAVA_KALİTESİ': '😷 Hava Kalitesi',
  DIGER: '📌 Diğer',
}